services:
  vault:
    container_name: vault
    hostname: vault
    image: hashicorp/vault:1.21.4
    restart: unless-stopped
    command: server
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=http://127.0.0.1:8300
      - VAULT_API_ADDR=https://vault.imetric.arpa
    volumes:
      - /opt/homelab/data/vault:/vault/file
      - /opt/homelab/configs/vault:/vault/config
    networks:
      - internal
      - reverse_proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=reverse_proxy
      - traefik.http.routers.vault.rule=Host(`vault.imetric.arpa`)
      - traefik.http.routers.vault.entrypoints=websecure
      - traefik.http.routers.vault.tls=true
      - traefik.http.services.vault.loadbalancer.server.port=8300
      - traefik.http.services.vault.loadbalancer.server.scheme=http
    healthcheck:
      # test: ["CMD", "vault", "status", "-address=http://127.0.0.1:8300"]
      test: ["CMD-SHELL", "vault status -address=http://127.0.0.1:8300 || [ $? -eq 2 ]"]
      interval: 30s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  internal:
    external: true
  reverse_proxy:
    external: true

