services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:7.4.10-alpine3.21
    restart: unless-stopped
    secrets:
      - redis_password
    entrypoint: ["sh", "-c"]
    command:
      - >
        redis-server
        --appendonly yes
        --requirepass "$$(cat /run/secrets/redis_password)"
    volumes:
      - /opt/homelab/data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--pass", "$$(cat /run/secrets/redis_password)", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

secrets:
  redis_password:
    file: /opt/homelab/secrets/redis_password

networks:
  internal:
    external: true

