services:
  grafana:
    container_name: grafana
    image: grafana/grafana:13.2.3
    restart: unless-stopped
    mem_limit: 512m
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    secrets:
      - grafana_admin_password
      - grafana_oauth_secret
    environment:
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin_password
      GF_SERVER_DOMAIN: grafana.home.arpa
      GF_SERVER_ROOT_URL: https://grafana.home.arpa
      GF_SECURITY_COOKIE_SECURE: "true"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_ANALYTICS_REPORTING_ENABLED: "false"

      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: authentik
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "AxRBRFrcPdU57JDTOUZZNRumGdGDOwHDvuMeSDCc"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET__FILE: /run/secrets/grafana_oauth_secret
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid email profile"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://auth.home.arpa/application/o/authorize/
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: https://auth.home.arpa/application/o/token/
      GF_AUTH_GENERIC_OAUTH_API_URL: https://auth.home.arpa/application/o/userinfo/
      GF_AUTH_SIGNOUT_REDIRECT_URL: https://auth.home.arpa/application/o/grafana/end-session/
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "'Admin'"
      SSL_CERT_FILE: /etc/ssl/certs/home-arpa-bundle.crt

    volumes:
      - /opt/homelab/data/grafana:/var/lib/grafana
      - /opt/homelab/configs/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - /opt/homelab/ssl/certs/home-arpa/ca-bundle.crt:/etc/ssl/certs/home-arpa-bundle.crt:ro
    
    networks:
      - monitoring
      - reverse_proxy
    
    labels:
      - traefik.enable=true
      - traefik.docker.network=reverse_proxy
      - traefik.http.routers.grafana.rule=Host(`grafana.home.arpa`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls=true
      - traefik.http.services.grafana.loadbalancer.server.port=3000

secrets:
  grafana_admin_password:
    file: /opt/homelab/secrets/grafana_admin_password
  grafana_oauth_secret:
    file: /opt/homelab/secrets/grafana_oauth_secret

networks:
  monitoring:
    external: true
  reverse_proxy:
    external: true
