services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - /opt/homelab/data/adguard/work:/opt/adguardhome/work
      - /opt/homelab/data/adguard/conf:/opt/adguardhome/conf
    networks:
      - reverse_proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard.rule=Host(`adguard.imetric.arpa`)
      - traefik.http.routers.adguard.entrypoints=websecure
      - traefik.http.routers.adguard.tls=true
      - traefik.http.services.adguard.loadbalancer.server.port=3000

networks:
  reverse_proxy:
    external: true
