services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:2
    restart: unless-stopped
    volumes:
      - /opt/homelab/data/uptime-kuma:/app/data
    networks:
      - reverse_proxy
      - monitoring
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptimekuma.rule=Host(`status.imetric.arpa`)
      - traefik.http.routers.uptimekuma.entrypoints=websecure
      - traefik.http.routers.uptimekuma.tls=true
      - traefik.http.services.uptimekuma.loadbalancer.server.port=3001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  reverse_proxy:
    external: true
  monitoring:
    external: true
